#!/usr/bin/env python

import subprocess

#global variable
commands=["rpm -qa | egrep 'HEB_Tomcat9|HEB_tomcat-'",]
tomcat_version='HEB_Tomcat9-9.0.54-150.el7.centos.x86_64'
#reading from file
with open('readme.txt') as f:
    hosts = f.readlines()



#looping through file and sshing to server and executing command
for host,command in zip(hosts,commands):
    HOST=host.strip()
#sshing to server
    print(HOST)
    ssh = subprocess.Popen(["ssh", HOST , command],
                       shell=False,
                       stdout=subprocess.PIPE,
                       stderr=subprocess.PIPE)
    result = ssh.stdout.readlines()
    result= b''.join(result)
    result=result.decode("utf-8")
    result=str(result.strip())
    if tomcat_version==result:
     print("Tomcat is updated, The version is :", result)
    else:
     print("Tomcat is note updated")
